### ISSUE TITLE
Please update NPM

### ISSUE THREAD

**Issue by tommoor** [deloreanjs/delorean#61]
Latest version on NPM is 0.8.5, the docs are related to 0.8.7

Just lost an hour of my day to this :frowning:

**Comment by tommoor** [comment]
@darcyadams do you have access to this, it's now way behind.

**Comment by darcyadams** [comment]
sadly @f has not given me npm access :disappointed: (@f, if you get an opportunity, would be awesome if you could give me access, 

@tbranyen - anyway you can publish a `0.9.0` release on npm for us? either that or make me an owner on npm (@darcyadams)

**Comment by tbranyen** [comment]
@tommoor I'm sorry you lost a day to this, but this is really chalked up to user error.  Always *always* check your package versions.  Then check them again via `npm ls` to ensure you are running exactly what you think you are.  If you don't want to trust what's in NPM you can always download directly from GitHub in your package.json with: `"delorean": "deloreanjs/delorean#0.8.7"`

I haven't used delorean in a while, but let me see if I can get the latest tag published.

**Comment by tbranyen** [comment]
Looks like this has already been updated and as there is no 0.9.0 tag, I cannot publish a new version.

**Comment by darcyadams** [comment]
@tbranyen - https://github.com/deloreanjs/delorean/releases/tag/0.9.0

**Comment by tjwebb** [comment]
Not sure why this is so hard.

```
npm version patch
git push --tags
npm publish
```
done. Or since this has CI, have CI auto-deploy passing builds. The maintainer can set this up in 5 minutes.

**Comment by darcyadams** [comment]
@tbranyen would you mind just making me an npm owner? @f [put me in charge of this project](https://github.com/deloreanjs/delorean/issues/65) while he is in the miitary, so we are in kind of a bind with no npm control. thanks.

**Comment by tbranyen** [comment]
Oh snap didn't realize that's where @f disappeared off to! Sure thing!

**Comment by darcyadams** [comment]
@tbranyen - should just be...
`npm owner add darcyadams delorean`

after you `npm login`

thanks

**Comment by tbranyen** [comment]
All set @darcyadams!

**Comment by darcyadams** [comment]
Thanks!

**Comment by darcyadams** [comment]
okay, new version finally published.
