### ISSUE TITLE
set method creates keys on store itself

### ISSUE THREAD

**Issue by tommoor** [deloreanjs/delorean#64]
Using the set method to set keys that are in the scheme it seems as though the data is set on the store object itself, wouldn't it make more sense to have some sort of data object within the store so that these properties aren't mixed in with other methods?

Maybe I'm missing something...

**Comment by darcyadams** [comment]
I agree. Been hoping to get around to this for awhile, but haven't gotten around to it. If you want to take a stab, go for it. 
I must say, it is handy to have them as top level attributes when you need to do data manipulation as opposed to setting, but I agree that the potential for accidental conflicts outweighs that minor benefit.

**Comment by tommoor** [comment]
Okay, glad I'm not going crazy - I also expected there to be some sort of default getState method implemented and I ended up just having to do:

```
getState: function() {
  return this;
}
```

which isn't great.

**Comment by darcyadams** [comment]
Well, the benefit of using scheme is that the scheme attributes are automatically applied as state in the views with the flux mixin. If you don't use scheme, yes you have to manually define a getState method.

**Comment by darcyadams** [comment]
... Actually the need to define the getStae method is what led to the initial idea for the scheme enhancement.

**Comment by tommoor** [comment]
Got it, this is useful. I guess the problem is that only a few of our stores are treated like models, the majority are used as the flux architecture expects - more like a collection of models. This is why I ended up implementing a getState method so that there was a consistent way to access the data across these different types of stores.

Ideally the scheme methodology would work with a collection as well and implement a standard method to get as well as set the data imo.

**Comment by darcyadams** [comment]
closing as this is now corrected in master
