### ISSUE TITLE
Will be unavailable for 5 months.

### ISSUE THREAD

**Issue by f** [deloreanjs/delorean#65]
Hey @darcyadams!

I'll be at army for my military obligation for ~5 months, so I cannot care on project.

Please take care of this project :)

**Comment by larukedi** [comment]
"hayirli teskereler"

**Comment by aybarscengaver** [comment]
"hayirli teskereler"

**Comment by bahattincinic** [comment]
"hayirli teskereler"

**Comment by ugurerkan** [comment]
"hayirli teskereler"

**Comment by burakcan** [comment]
"hayirli teskereler"

**Comment by darcyadams** [comment]
@f np! You got it. It's in good hands.

**Comment by darcyadams** [comment]
@f np! You got it. It's in good hands.

**Comment by yuxel** [comment]
"hayırlı testereler"

**Comment by onderozcan** [comment]
"hayirli teskereler"

**Comment by safakotur** [comment]
"hayirli teskereler"

**Comment by onderozcan** [comment]
https://www.youtube.com/watch?v=UfmgnGXqXaw

**Comment by Ardakilic** [comment]
"hayirli teskereler"

**Comment by cangoktas** [comment]
"hayirli teskereler"

**Comment by ismailbaskin** [comment]
hayırlı teZkereler

**Comment by smtaydemir** [comment]
"hayirli teskereler"

**Comment by halitalptekin** [comment]
"hayirli teskereler"

**Comment by hmert** [comment]
hayırlı tekzereler

**Comment by onderozcan** [comment]
hayırlı tekzereler
