### ISSUE TITLE
Is delorean dead?

### ISSUE THREAD

**Issue by jantimon** [deloreanjs/delorean#76]
All jsfiddle links seems to be broken and recompiling the example also causes the app to break.  
Was this project abandoned?

**Comment by darcyadams** [comment]
No, it is very much alive. We'll take a look at the fiddles. The founder is temporarily unavailable, so we are doing our best while not having access to all the resources.

**Comment by jantimon** [comment]
Alright - thanks for the fast response.  
Are there any working examples for the current version?

**Comment by darcyadams** [comment]
Not actually sure. But the docs are up to date.
