### ISSUE TITLE
Throw error when attempting to access a store that isn't watched in mixin

### ISSUE THREAD

**Issue by tommoor** [deloreanjs/delorean#78]
Our engineers keep getting caught out by this. You use getStore in the react mixin but forget to include the relevant store in the watchStores list.

We could prevent a lot of debugging pain by simply throwing an error in this instance :smile:

**Comment by darcyadams** [comment]
good idea. As long as you stick to `getStore` and don't attempt to access `this.state.stores.unwatchedStore` within render, then we can warn. 
I would definitely merge a pr with this enhancement 😉

**Comment by darcyadams** [comment]
[PR](https://github.com/deloreanjs/delorean/pull/80) opened.
