### ISSUE TITLE
Ractive example fix

### ISSUE THREAD

**Issue by peterdenev** [deloreanjs/delorean#92]
The Ractive example did not work.
Here is my fix 
http://jsfiddle.net/2r1k2k90/33/

**Comment by f** [comment]
Thanks! https://github.com/deloreanjs/delorean/commit/44ca1fa6e0a3a94682857a2599d0059701280dec

**Comment by f** [comment]
Also: https://github.com/deloreanjs/delorean/commit/8afadd98fc5ff39ca5e2627563f815d06066fe5d

**Comment by peterdenev** [comment]
You can also change the link in your site http://deloreanjs.com/
